feat: implement user service (#3)
wizeline/CA-Microservices-Go pull request #37
Opened 2024-03-19 05:47 UTC by maritza05

Implementation of the user service.

2024-03-19 19:31 UTC, maritza05 commented on internal/service/user.go
>  func (s UserService) Add(user entity.User) (int, error) {
Remove int return value.

2024-03-19 19:38 UTC, maritza05 commented on internal/service/user.go
> +	err := s.repo.Create(user)
Add validation and create a new error for validation.

2024-03-19 19:50 UTC, maritza05 commented on internal/service/user_test.go
> +				assert.Contains(t, gotErr.Error(), tt.wantErrMessage)
Validate that I got the same error.

2024-03-19 20:02 UTC, maritza05 commented on internal/service/user_test.go
> +			s := NewUser(mockRepo)
Change the new method to be newUserService

2024-04-12 23:36 UTC, maritza05 commented on internal/service/user.go
> +	Read(id uint64) (entity.User, error)
Changed the repo's interface to prevent lost of information

2024-04-13 14:54 UTC, marcos-wz requested changes
LGTM. Just minor changes

2024-04-13 14:54 UTC, marcos-wz commented on internal/service/error.go
> +var InvalidPassword = errors.New("Can't login, passwords doesn't match")
This is a small fix. The block of variable definitions use to be at the top of the file after the library import section.

2024-04-13 14:54 UTC, marcos-wz commented on internal/service/user.go
> +	"slices"
Small fix. In Go is a good practice follow an importing order:  standard libraries, our libraries, third-party libraries

2024-04-13 14:54 UTC, marcos-wz commented on internal/service/user.go
> +	return user, nil
We could go straight forward and return from `s.repo.Read` function as the responses are the same. It allows reduce the code to a one-line function `return s.repo.Read(id)`

2024-04-14 22:05 UTC, marcos-wz requested changes
Integration issues

2024-04-14 22:05 UTC, marcos-wz commented on internal/service/user.go
> +	if users[0].Passwd == password {
We can't validate a plain password vs a hashed password. I suspect we should implement a ValidateLogin function in the repository implementation or add more logic in the service function

2024-04-20 23:07 UTC, marcos-wz approved these changes

2024-04-20 23:07 UTC, merged